stages:
  prepare-residentials-metadata:
    cmd: python ./preparation/residential_metadata.py -o ./residentials-metadata.parquet
    outs:
      - ./residentials-metadata.parquet

  prepare-residentials:
    cmd: python ./preparation/residential.py -i ../../data/raw/HUE/Residential_*.csv -o ./residentials.parquet
    deps:
      - ../../data/raw/HUE/Residential_1.csv
      - ../../data/raw/HUE/Residential_2.csv
      - ../../data/raw/HUE/Residential_3.csv
      - ../../data/raw/HUE/Residential_4.csv
      - ../../data/raw/HUE/Residential_5.csv
      - ../../data/raw/HUE/Residential_6.csv
      - ../../data/raw/HUE/Residential_7.csv
      - ../../data/raw/HUE/Residential_8.csv
      - ../../data/raw/HUE/Residential_9.csv
      - ../../data/raw/HUE/Residential_10.csv
      - ../../data/raw/HUE/Residential_11.csv
      - ../../data/raw/HUE/Residential_12.csv
      - ../../data/raw/HUE/Residential_13.csv
      - ../../data/raw/HUE/Residential_14.csv
      - ../../data/raw/HUE/Residential_15.csv
      - ../../data/raw/HUE/Residential_16.csv
      - ../../data/raw/HUE/Residential_17.csv
      - ../../data/raw/HUE/Residential_18.csv
      - ../../data/raw/HUE/Residential_19.csv
      - ../../data/raw/HUE/Residential_20.csv
      - ../../data/raw/HUE/Residential_21.csv
      - ../../data/raw/HUE/Residential_22.csv
      - ../../data/raw/HUE/Residential_23.csv
      - ../../data/raw/HUE/Residential_24.csv
      - ../../data/raw/HUE/Residential_25.csv
      - ../../data/raw/HUE/Residential_26.csv
      - ../../data/raw/HUE/Residential_27.csv
      - ../../data/raw/HUE/Residential_28.csv

    outs:
      - ./residentials.parquet

  prepare-weather:
    cmd: python ./preparation/weather.py -i ../../data/raw/HUE/Weather_*.csv -o ./weather.parquet
    deps:
      - ../../data/raw/HUE/Weather_WYJ.csv
      - ../../data/raw/HUE/Weather_YVR.csv
    outs:
      - ./weather.parquet


  enrich-features:
    cmd: python enrich.py -o ./features.parquet
    deps:
      - ./weather.parquet
      - ./residentials.parquet
      - ./residentials-metadata.parquet
    outs:
      - ./features.parquet