version: '3'
services:
  spark-master:
    image: bde2020/spark-master:3.2.0-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - ../../data:/media:ro

  spark-worker-1:
    image: bde2020/spark-worker:3.2.0-hadoop3.2
    container_name: spark-worker-1
    command: bash -c "pip3 install -U pysolar holidays pytz && /bin/bash /worker.sh"
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - ../../data:/media:ro

  spark-history-server:
    image: bde2020/spark-history-server:3.2.0-hadoop3.2
    container_name: spark-history-server
    depends_on:
      - spark-master
    ports:
      - "18081:18081"
    volumes:
      - /tmp/spark-events-local:/tmp/spark-events

  spark-client:
    build: .
    container_name: spark-client
    depends_on:
      - spark-master
      - spark-worker-1
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - ../../data:/media:ro
      - .:/app